# Generated by Django 2.0.3 on 2018-09-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('please_marketing_app', '0077_auto_20180920_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEnrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=500)),
                ('buy_low_price', models.FloatField(blank=True, null=True)),
                ('buy_medium_price', models.FloatField(blank=True, null=True)),
                ('buy_high_price', models.FloatField(blank=True, null=True)),
                ('rent_low_price', models.FloatField(blank=True, null=True)),
                ('rent_medium_price', models.FloatField(blank=True, null=True)),
                ('rent_high_price', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FullContactApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('json_response', models.CharField(blank=True, max_length=500000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
