# Generated by Django 2.0.3 on 2018-10-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_extra_user_enrichment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressenrichment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='addressenrichment',
            name='street',
        ),
        migrations.RemoveField(
            model_name='addressenrichment',
            name='zip',
        ),
    ]
