# Generated by Django 2.0.3 on 2019-04-19 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0097_auto_20190419_1245'),
        ('please_marketing_extra_user_enrichment', '0002_auto_20181016_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEnrichmentSl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=150, null=True)),
                ('longitude', models.CharField(blank=True, max_length=150, null=True)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
                ('cp', models.CharField(blank=True, max_length=150, null=True)),
                ('summary_prices_max', models.FloatField(blank=True, null=True)),
                ('summary_prices_med', models.FloatField(blank=True, null=True)),
                ('summary_prices_min', models.FloatField(blank=True, null=True)),
                ('market_numbers_selling', models.FloatField(blank=True, null=True)),
                ('market_numbers_sold', models.FloatField(blank=True, null=True)),
                ('market_numbers_numberMainResidence', models.FloatField(blank=True, null=True)),
                ('market_numbers_numberSecondaryResidence', models.FloatField(blank=True, null=True)),
                ('market_numbers_numberTotalResidence', models.FloatField(blank=True, null=True)),
                ('single', models.IntegerField(blank=True, null=True)),
                ('couple', models.IntegerField(blank=True, null=True)),
                ('family', models.IntegerField(blank=True, null=True)),
                ('poi_transport_count', models.IntegerField(blank=True, null=True)),
                ('poi_education_count', models.IntegerField(blank=True, null=True)),
                ('poi_neighbors_count', models.IntegerField(blank=True, null=True)),
                ('poi_hotels_count', models.IntegerField(blank=True, null=True)),
                ('poi_commerces_count', models.IntegerField(blank=True, null=True)),
                ('nbLogements', models.IntegerField(blank=True, null=True)),
                ('nbHabitants', models.IntegerField(blank=True, null=True)),
                ('peopleDensity', models.IntegerField(blank=True, null=True)),
                ('ageMed', models.IntegerField(blank=True, null=True)),
                ('age25MoinsPcent', models.IntegerField(blank=True, null=True)),
                ('age25PlusPcent', models.IntegerField(blank=True, null=True)),
                ('nbEntreprises', models.IntegerField(blank=True, null=True)),
                ('nbCreationEntreprises', models.IntegerField(blank=True, null=True)),
                ('pcentActifsAll', models.IntegerField(blank=True, null=True)),
                ('pcentActifs30', models.IntegerField(blank=True, null=True)),
                ('pcentUnemployed', models.IntegerField(blank=True, null=True)),
                ('averageIncome', models.IntegerField(blank=True, null=True)),
                ('pcentEtudiants', models.IntegerField(blank=True, null=True)),
                ('pcentResPrincipales', models.IntegerField(blank=True, null=True)),
                ('pcentResSecondaires', models.IntegerField(blank=True, null=True)),
                ('pcentLogVacants', models.IntegerField(blank=True, null=True)),
                ('pcentLocataires', models.IntegerField(blank=True, null=True)),
                ('pcentPrpriotaires', models.IntegerField(blank=True, null=True)),
                ('pcentAppartement', models.IntegerField(blank=True, null=True)),
                ('pcentMaisons', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer')),
            ],
        ),
    ]
