# Generated by Django 2.0.3 on 2019-04-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_extra_user_enrichment', '0003_addressenrichmentsl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullContactApi',
        ),
    ]
