# Generated by Django 2.0.3 on 2019-03-01 11:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('please_marketing_app', '0093_merchant_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPictureSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsplash_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('picture_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25, null=True), blank=True, null=True, size=None)),
                ('match_type', models.CharField(choices=[('sm', 'Safe Match'), ('rm', 'Risky Match')], default='rm', max_length=2)),
                ('ranking_search', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Merchant')),
            ],
        ),
    ]
