# Generated by Django 2.0.3 on 2019-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpicturesource',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantpicturesource',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
