# Generated by Django 2.0.3 on 2019-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.CharField(choices=[('mlp', 'Mobile Landing Page'), ('mlpa', 'Mobile Landing Page Alert'), ('mlpad', 'Mobile Landing Page Alert Done'), ('mlps', 'Mobile Landing Page Signup'), ('dlp', 'Desktop Landing Page'), ('dlpa', 'Desktop Landing Page Alert'), ('dlpad', 'Desktop Landing Page Alert Done'), ('dlps', 'Desktop Landing Page Signup')], default='mlp', max_length=10)),
                ('image_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_type', models.CharField(choices=[('hr', 'Header'), ('lo', 'Logo')], default='hr', max_length=2)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='landing_pages/pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.CharField(choices=[('mlp', 'Mobile Landing Page'), ('mlpa', 'Mobile Landing Page Alert'), ('mlpad', 'Mobile Landing Page Alert Done'), ('mlps', 'Mobile Landing Page Signup'), ('dlp', 'Desktop Landing Page'), ('dlpa', 'Desktop Landing Page Alert'), ('dlpad', 'Desktop Landing Page Alert Done'), ('dlps', 'Desktop Landing Page Signup')], default='mlp', max_length=10)),
                ('text_name', models.CharField(blank=True, max_length=100, null=True)),
                ('text_type', models.CharField(choices=[('hr', 'Header'), ('sr', 'Sub Header'), ('bn', 'Button')], default='hr', help_text='<span> text <span> pour mettre du texte en jaune', max_length=2)),
                ('text', models.TextField(default='Lorem Ipsum', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign_keywords',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign_search_terms',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign_zip',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='landing_page_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sent_to_intercom',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='user_agent_data',
        ),
    ]
