# Generated by Django 2.0.3 on 2019-03-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_landing_pages', '0004_auto_20190304_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageimage',
            name='target_page',
            field=models.CharField(choices=[('lpa', 'Landing Page Alert'), ('lpad', 'Landing Page Alert Done'), ('lps', 'Landing Page Signup')], default='lp', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingpagetext',
            name='target_page',
            field=models.CharField(choices=[('lpa', 'Landing Page Alert'), ('lpad', 'Landing Page Alert Done'), ('lps', 'Landing Page Signup')], default='lp', max_length=10),
        ),
    ]
