# Generated by Django 2.0.3 on 2019-06-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0106_auto_20190603_1517'),
        ('please_marketing_landing_pages', '0008_auto_20190513_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='img_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Neighborhood'),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_term',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='txt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
