"""
Django settings for please_marketing project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'please-marketing-staging.herokuapp.com',
    'please-marketing-production.herokuapp.com',
    'hello.pleaseapp.com',
    'hello-dev.pleaseapp.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'storages',
    'cloudinary',
    'please_marketing_app',
    'please_marketing_referral_program',
    'please_marketing_growth_hack',
    'please_marketing_recommendation',
    'please_marketing_leaderboard',
    'please_marketing_extra_user_enrichment',
    'please_marketing_script_execution',
    'please_marketing_etl',
    'please_marketing_campaign',
    'please_marketing_landing_pages',
    'please_marketing_pictures',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'please_marketing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'please_marketing_referral_program/templates'),
            os.path.join(BASE_DIR, 'please_marketing_leaderboard/templates'),
            os.path.join(BASE_DIR, 'please_marketing_recommendation/templates'),
            os.path.join(BASE_DIR, 'please_marketing_growth_hack/templates'),
            os.path.join(BASE_DIR, 'please_marketing_campaign/templates'),
            os.path.join(BASE_DIR, 'please_marketing_landing_pages/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'please_marketing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ["DB_NAME"],
        'USER': os.environ["DB_USER"],
        'PASSWORD': os.environ["DB_PASSWORD"],
        'HOST': os.environ["DB_HOST"],
        'PORT': os.environ["DB_PORT"],
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# SECURITY
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True

# ADMINS
ADMINS = (
    ('Nicolas Chanton', 'nicolas.chanton@gmail.com'),
)

# EMAIL CONFIGURATION
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
#DEFAULT_FROM_EMAIL = os.environ["DEFAULT_FROM_EMAIL"]
#EMAIL_HOST = os.environ["EMAIL_HOST"]
#EMAIL_HOST_USER = os.environ["EMAIL_HOST_USER"]
#EMAIL_HOST_PASSWORD = os.environ["EMAIL_HOST_PASSWORD"]
#EMAIL_USE_TLS = True
#EMAIL_PORT = os.environ["EMAIL_PORT"]
SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
SENDGRID_SANDBOX_MODE_IN_DEBUG = False


# STATIC FILES CONFIGURATION
#STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
#print("Static ROOT", STATIC_ROOT)
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA FILES CONFIGURATION
AWS_ACCESS_KEY_ID = os.environ["AWS_KEY_ID"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_KEY_SECRET"]
AWS_FILE_EXPIRE = 200
AWS_PRELOAD_METADATA = True
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = "public-read"

DEFAULT_FILE_STORAGE = 'please_marketing.aws.utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'please_marketing.aws.utils.StaticRootS3BotoStorage'

AWS_STORAGE_BUCKET_NAME = os.environ["AWS_BUCKET_NAME"]
S3DIRECT_REGION = 'eu-west-3'
S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
MEDIA_URL = '//%s.s3.amazonaws.com/media/' % AWS_STORAGE_BUCKET_NAME
MEDIA_ROOT = MEDIA_URL
STATIC_URL = S3_URL + 'static/'
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'

two_months = datetime.timedelta(days=61)
date_two_months_later = datetime.date.today() + two_months
expires = date_two_months_later.strftime("%A, %d %B %Y 20:00:00 GMT")

AWS_HEADERS = {
    'Expires': expires,
    'Cache-Control': 'max-age=%d' % (int(two_months.total_seconds()), ),
}


# CLOUDINARY CONFIGURATION
CLOUDINARY_URL = os.environ["CLOUDINARY_URL"]
CLOUDINARY_CLOUD_NAME = os.environ["CLOUDINARY_CLOUD_NAME"]
CLOUDINARY_API_KEY = os.environ["CLOUDINARY_API_KEY"]
CLOUDINARY_API_SECRET = os.environ["CLOUDINARY_API_SECRET"]


# TWILIO CONFIGURATION
TWILIO_SID = os.environ["TWILIO_SID"]
TWILIO_TOKEN = os.environ["TWILIO_TOKEN"]
TWILIO_PHONE = os.environ["TWILIO_PHONE"]
TWILIO_PHONE_PLAIN = os.environ["TWILIO_PHONE_PLAIN"]

# INTERCOM CONFIGURATION
INTERCOM_KEY = os.environ["INTERCOM_KEY"]
INTERCOM_HUB_SECRET = os.environ["INTERCOM_HUB_SECRET"]

# AMPLITUDE CONFIGURATION
AMPLITUDE_KEY = os.environ["AMPLITUDE_KEY"]

# GENDER CONFIGURATION
GENDER_KEY = os.environ["GENDER_KEY"]

# FULL CONTACT CONFIGURATION
FULLCONTACT_KEY = os.environ["FULLCONTACT_KEY"]

# PLEASE MW ACCESS
PLEASE_MW_TOKEN = os.environ["PLEASE_MW_TOKEN"]

# PROXICITY KEY
PROXICITY_KEY = os.environ["PROXICITY_KEY"]

# CRON_TEST_USER
CRON_TEST_USER = os.environ["CRON_TEST_USER"]

# GOOGLE API
GOOGLE_GEOCODING_KEY = os.environ["GOOGLE_GEOCODING_KEY"]
GOOGLE_API_KEY = os.environ["GOOGLE_API_KEY"]

# IP API
IP_API_KEY = os.environ["IP_API_KEY"]

# USER PERSO SECRET
PLEASE_MARKET_SECRET = os.environ["PLEASE_MARKET_SECRET"]

# ODOO
ODOO_USERNAME = os.environ["ODOO_USERNAME"]
ODOO_PASSWORD = os.environ["ODOO_PASSWORD"]
ODOO_DB_NAME = os.environ["ODOO_DB_NAME"]
ODOO_URL = os.environ["ODOO_URL"]
ODOO_PARTNER_HASH = os.environ["ODOO_PARTNER_HASH"]

# DB ODOO
DB_ODOO_HOST = os.environ["DB_ODOO_HOST"]
DB_ODOO_NAME = os.environ["DB_ODOO_NAME"]
DB_ODOO_PASSWORD = os.environ["DB_ODOO_PASSWORD"]
DB_ODOO_PORT = os.environ["DB_ODOO_PORT"]
DB_ODOO_USER = os.environ["DB_ODOO_USER"]

# DB MW
DB_MW_HOST = os.environ["DB_MW_HOST"]
DB_MW_NAME = os.environ["DB_MW_NAME"]
DB_MW_PASSWORD = os.environ["DB_MW_PASSWORD"]
DB_MW_PORT = os.environ["DB_MW_PORT"]
DB_MW_USER = os.environ["DB_MW_USER"]

# DB DJANGO
DB_HOST = os.environ["DB_HOST"]
DB_NAME = os.environ["DB_NAME"]
DB_PASSWORD = os.environ["DB_PASSWORD"]
DB_PORT = os.environ["DB_PORT"]
DB_USER = os.environ["DB_USER"]


# DB PLEASE PRO WEBSITE
DB_PP_HOST = os.environ["DB_PP_HOST"]
DB_PP_NAME = os.environ["DB_PP_NAME"]
DB_PP_PASSWORD = os.environ["DB_PP_PASSWORD"]
DB_PP_PORT = os.environ["DB_PP_PORT"]
DB_PP_USER = os.environ["DB_PP_USER"]
