# Generated by Django 2.0.3 on 2018-09-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('please_marketing_app', '0077_auto_20180920_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardVoucherCityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_period_date', models.DateField(blank=True, max_length=500, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('city_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.CityManager')),
            ],
        ),
    ]
