# Generated by Django 2.0.3 on 2018-12-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_growth_hack', '0004_auto_20181116_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lbcphone',
            name='lbc_url',
        ),
        migrations.RemoveField(
            model_name='lbcurl',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='LbcPhone',
        ),
        migrations.DeleteModel(
            name='LbcUrl',
        ),
    ]
