# Generated by Django 2.0.3 on 2019-01-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0088_citymanager_customer'),
        ('please_marketing_growth_hack', '0006_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Merchant'),
        ),
    ]
