# Generated by Django 2.0.3 on 2019-01-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_growth_hack', '0007_lead_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='raw_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
