# Generated by Django 2.0.3 on 2019-03-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0096_auto_20190315_1340'),
        ('please_marketing_growth_hack', '0009_gamevoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVoucherVernon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=10, null=True)),
                ('voucher_value', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Merchant')),
            ],
        ),
    ]
