# Generated by Django 2.0.3 on 2019-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_growth_hack', '0010_gamevouchervernon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
