# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='average_basket',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='housing_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='housing_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='housing_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='session_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sign_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_voucher',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fete',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fete',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fete',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='basket_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='please_marketing_app.Customer'),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='delivery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='event_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='intercom_user_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='partner_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='please_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='point_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='user_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='voucher_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='odoo_order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='odoo_price_list_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_neighborhood',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_delivery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='label',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='odoo_order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='odoo_order_line_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
