# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0003_auto_20171217_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
