# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0006_auto_20171219_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='please_marketing_app.Neighborhood'),
        ),
    ]
