# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0010_auto_20171220_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='inside_perimeter',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
