# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0011_auto_20171220_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='click_and_collect',
            field=models.BooleanField(default=False),
        ),
    ]
