# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0012_auto_20171221_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercomevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='intercom_user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
