# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0014_auto_20180124_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='face_analysis',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='inside_perimeter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_url_facebook',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_url_google',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_url_instagram',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_url_linkedin',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_url_twitter',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='odoo_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='offer_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='search_term',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='mw_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='odoo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
