# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0015_auto_20180209_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='family',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='inside_perimeter',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signed_up',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unsubscribed_from_emails',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='intercomevent',
            name='sent_to_amplitude',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='click_and_collect',
            field=models.NullBooleanField(),
        ),
    ]
