# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0016_auto_20180209_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='please_marketing_app.Neighborhood'),
        ),
    ]
