# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 22:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0017_intercomevent_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercomevent',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2000, null=True), blank=True, null=True, size=None),
        ),
    ]
