# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0020_customer_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intercomevent',
            old_name='intercom_user_id',
            new_name='intercom_id',
        ),
    ]
