# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0021_auto_20180213_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='intercom_user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
