# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0022_intercomevent_intercom_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='minimum_basket_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
