# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0024_auto_20180214_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercomevent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='intercomevent',
            name='language',
        ),
        migrations.RemoveField(
            model_name='intercomevent',
            name='region',
        ),
    ]
