# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0025_auto_20180215_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='delivery_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street',
            new_name='delivery_street',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='delivery_zip',
        ),
        migrations.RemoveField(
            model_name='intercomevent',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_order',
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='click_and_collect',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='delivery_zip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='basket_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='please_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
