# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0028_auto_20180216_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='universe',
            new_name='universe_name',
        ),
        migrations.RemoveField(
            model_name='intercomevent',
            name='offer_list',
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='offer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='universe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='universe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
