# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0029_auto_20180218_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='updated_ip',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='updated_neighborhood',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='updated_order',
            field=models.NullBooleanField(),
        ),
    ]
