# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 15:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0031_auto_20180222_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='categories_purchased',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='merchants_purchased',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='universes_purchased',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vouchers_used',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cb',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
    ]
