# Generated by Django 2.0.3 on 2018-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0034_auto_20180326_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_id',
            new_name='mw_offer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='supplier_id',
            new_name='mw_supplier_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='universe_id',
            new_name='mw_universe_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='odoo_price_list_id',
            new_name='odoo_offer_id',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='odoo_supplier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='odoo_universe_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
