# Generated by Django 2.0.3 on 2018-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0035_auto_20180326_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='customer',
            name='marked_email_as_spam',
            field=models.NullBooleanField(),
        ),
    ]
