# Generated by Django 2.0.3 on 2018-05-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0037_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='discovery_notif_to_be_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='first_notif_to_be_sent',
            field=models.BooleanField(default=False),
        ),
    ]
