# Generated by Django 2.0.3 on 2018-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0038_auto_20180508_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='voucher_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
