# Generated by Django 2.0.3 on 2018-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0042_auto_20180516_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullContactApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('json_response', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
