# Generated by Django 2.0.3 on 2018-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0044_auto_20180516_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcontactapi',
            name='json_response',
            field=models.CharField(blank=True, max_length=500000, null=True),
        ),
    ]
