# Generated by Django 2.0.3 on 2018-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0045_auto_20180517_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='em_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='em_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='em_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='third_best',
            field=models.NullBooleanField(),
        ),
    ]
