# Generated by Django 2.0.3 on 2018-05-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0046_auto_20180517_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='em_picture_2',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='em_picture_3',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
