# Generated by Django 2.0.3 on 2018-05-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0048_auto_20180517_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device_id',
        ),
    ]
