# Generated by Django 2.0.3 on 2018-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0049_remove_customer_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='user_agent_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
