# Generated by Django 2.0.3 on 2018-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0050_intercomevent_user_agent_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='first_notif_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='first_notif_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
