# Generated by Django 2.0.3 on 2018-05-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0051_auto_20180519_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='first_notif_hour',
        ),
    ]
