# Generated by Django 2.0.3 on 2018-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0052_remove_merchant_first_notif_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='first_notif_date',
            new_name='notif_date',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='first_notif_sent',
            new_name='notif_sent',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='first_notif_to_be_sent',
            new_name='notif_to_be_sent',
        ),
        migrations.AddField(
            model_name='merchant',
            name='rediscover',
            field=models.NullBooleanField(),
        ),
    ]
