# Generated by Django 2.0.3 on 2018-05-21 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0053_auto_20180519_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercomevent',
            name='channel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='intercomevent',
            name='offer_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2000, null=True), blank=True, null=True, size=None),
        ),
    ]
