# Generated by Django 2.0.3 on 2018-05-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0054_auto_20180521_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercomevent',
            name='updated_neighborhood',
        ),
        migrations.RemoveField(
            model_name='intercomevent',
            name='updated_order',
        ),
    ]
