# Generated by Django 2.0.3 on 2018-05-24 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0055_auto_20180521_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercomevent',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20000, null=True), blank=True, null=True, size=None),
        ),
    ]
