# Generated by Django 2.0.3 on 2018-06-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0057_customer_first_import_events_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('abandoned_cart', models.NullBooleanField()),
                ('abandoned_sign_up', models.NullBooleanField()),
                ('rediscover', models.NullBooleanField()),
                ('discover', models.NullBooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('abandoned_cart', models.NullBooleanField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
