# Generated by Django 2.0.3 on 2018-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0062_merchant_odoo_offers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='mw_offers_id',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='odoo_offers_id',
        ),
        migrations.AddField(
            model_name='merchant',
            name='mw_offer_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='odoo_offer_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
