# Generated by Django 2.0.3 on 2018-08-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0064_netpromoterscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchercode',
            name='abandoned_cart',
        ),
        migrations.RemoveField(
            model_name='vouchercode',
            name='sent',
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='notification_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='sent_to_customer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='value',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchercode',
            name='voucher_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='code',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
