# Generated by Django 2.0.3 on 2018-08-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0066_smshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchercode',
            name='sent_to_customer',
        ),
    ]
