# Generated by Django 2.0.3 on 2018-08-24 10:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0069_cosinesimilaritybooking_vectorbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorbooking',
            name='vector_merchant',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
