# Generated by Django 2.0.3 on 2018-08-29 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0070_vectorbooking_vector_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralmatch',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referee', to='please_marketing_app.Customer'),
        ),
        migrations.AddField(
            model_name='referralmatch',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referrer', to='please_marketing_app.Customer'),
        ),
    ]
