# Generated by Django 2.0.3 on 2018-08-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0071_auto_20180829_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_email', models.CharField(blank=True, max_length=500, null=True)),
                ('lead_sms', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer')),
            ],
        ),
    ]
