# Generated by Django 2.0.3 on 2018-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0073_auto_20180903_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archived',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing',
            field=models.NullBooleanField(),
        ),
    ]
