# Generated by Django 2.0.3 on 2018-09-14 16:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0074_auto_20180904_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('sent_comment_request', models.NullBooleanField()),
                ('referral_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('sent_comment_request', models.NullBooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_name', models.CharField(max_length=500)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='facebook_catalog_csv/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardVoucherCityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_period_date', models.DateField(blank=True, max_length=500, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('city_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.CityManager')),
            ],
        ),
        migrations.CreateModel(
            name='PleaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mw_item_id', models.IntegerField()),
                ('google_product_category', models.CharField(default='Food, Beverages & Tobacco > Food Items > Prepared Foods', max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('availability', models.CharField(default='in stock', max_length=500)),
                ('condition', models.CharField(default='new', max_length=500)),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=500)),
                ('image_link', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(max_length=70)),
                ('universe_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Merchant')),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='inhabitants_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Neighborhood'),
        ),
        migrations.AddField(
            model_name='citymanager',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Neighborhood'),
        ),
    ]
