# Generated by Django 2.0.3 on 2018-09-15 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0075_auto_20180914_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='zip_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), blank=True, null=True, size=None),
        ),
    ]
