# Generated by Django 2.0.3 on 2018-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0076_neighborhood_zip_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosinesimilaritybooking',
            name='customer_1',
        ),
        migrations.RemoveField(
            model_name='cosinesimilaritybooking',
            name='customer_2',
        ),
        migrations.DeleteModel(
            name='FacebookCatalog',
        ),
        migrations.DeleteModel(
            name='FullContactApi',
        ),
        migrations.RemoveField(
            model_name='leaderboardvouchercitymanager',
            name='city_manager',
        ),
        migrations.RemoveField(
            model_name='referrallead',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='referralmatch',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='referralmatch',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='vectorbooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='google_product_category',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='pleaseitem',
            name='mw_item_id',
        ),
        migrations.AddField(
            model_name='merchant',
            name='universe_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='CosineSimilarityBooking',
        ),
        migrations.DeleteModel(
            name='LeaderboardVoucherCityManager',
        ),
        migrations.DeleteModel(
            name='ReferralLead',
        ),
        migrations.DeleteModel(
            name='ReferralMatch',
        ),
        migrations.DeleteModel(
            name='VectorBooking',
        ),
    ]
