# Generated by Django 2.0.3 on 2018-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0077_auto_20180920_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_leads_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
