# Generated by Django 2.0.3 on 2018-09-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0078_customer_referral_leads_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.NullBooleanField(),
        ),
    ]
