# Generated by Django 2.0.3 on 2018-10-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0080_pleaseitem_mw_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='third_best',
            new_name='five_best',
        ),
        migrations.AddField(
            model_name='pleaseitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pictures/None/'),
        ),
    ]
