# Generated by Django 2.0.3 on 2018-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0081_auto_20181004_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleaseitem',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='em_picture_1',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='notif_date',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='notif_sent',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='notif_to_be_sent',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='rediscover',
        ),
        migrations.AddField(
            model_name='merchant',
            name='launch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='picture_banner',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/<django.db.models.fields.CharField>/banner/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='picture_square',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/<django.db.models.fields.CharField>/square/'),
        ),
        migrations.DeleteModel(
            name='PleaseItem',
        ),
    ]
