# Generated by Django 2.0.3 on 2018-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0082_auto_20181015_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='baned',
            field=models.NullBooleanField(),
        ),
    ]
