# Generated by Django 2.0.3 on 2018-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0083_customer_baned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
