# Generated by Django 2.0.3 on 2018-10-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0085_order_first_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='picture_banner',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/banner/'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='picture_square',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_pictures/square/'),
        ),
    ]
