# Generated by Django 2.0.3 on 2018-11-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0086_auto_20181029_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='launch_date',
        ),
    ]
