# Generated by Django 2.0.3 on 2018-11-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0087_remove_merchant_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymanager',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Customer'),
        ),
    ]
