# Generated by Django 2.0.3 on 2019-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0088_citymanager_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='picture_banner',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='picture_square',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='type',
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
