# Generated by Django 2.0.3 on 2019-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0089_auto_20190212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='universe_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
