# Generated by Django 2.0.3 on 2019-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0090_auto_20190212_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='picture_raw',
            field=models.ImageField(blank=True, null=True, upload_to='offers/pictures/presentation/'),
        ),
    ]
