# Generated by Django 2.0.3 on 2019-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0091_merchant_picture_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
