# Generated by Django 2.0.3 on 2019-02-28 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0092_auto_20190213_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None),
        ),
    ]
