# Generated by Django 2.0.3 on 2019-03-01 16:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0093_merchant_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='picture_raw',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
