# Generated by Django 2.0.3 on 2019-03-01 16:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0094_auto_20190301_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='picture_raw',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
