# Generated by Django 2.0.3 on 2019-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0095_auto_20190301_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='open',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='merchant',
            name='rating_number',
            field=models.IntegerField(default=1),
        ),
    ]
