# Generated by Django 2.0.3 on 2019-04-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0096_auto_20190315_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='housing_average',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='housing_high',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='housing_low',
        ),
    ]
