# Generated by Django 2.0.3 on 2019-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0103_deliverymanlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymanlead',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverymanlead',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymanlead',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
