# Generated by Django 2.0.3 on 2019-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0105_neighborhood_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='timezone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
