# Generated by Django 2.0.3 on 2019-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0107_salesanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesanalysis',
            name='average_basket',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='average_partner_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='average_please_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='order_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='po_vo_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='trending_orders_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalysis',
            name='trending_orders_60',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
