# Generated by Django 2.0.3 on 2019-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0108_auto_20190612_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesanalysis',
            name='average_basket_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_basket_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_basket_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_partner_amount_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_partner_amount_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_partner_amount_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_please_amount_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_please_amount_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_please_amount_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_rating_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_rating_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='average_rating_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='order_number_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='po_vo_ratio_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='po_vo_ratio_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='po_vo_ratio_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='viewed_offer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='viewed_offer_30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='viewed_offer_60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesanalysis',
            name='viewed_offer_trend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
