# Generated by Django 2.0.3 on 2019-06-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0109_auto_20190613_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesanalysis',
            old_name='trending_orders_30',
            new_name='order_number_30',
        ),
        migrations.RenameField(
            model_name='salesanalysis',
            old_name='trending_orders_60',
            new_name='order_number_60',
        ),
    ]
