# Generated by Django 2.0.3 on 2019-07-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0112_smsauthorizationinprogress_sms_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mw_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('unavailable', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('ingredients', models.CharField(blank=True, max_length=500, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
