# Generated by Django 2.0.3 on 2019-08-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0113_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='favourite_dish',
            field=models.CharField(blank=True, choices=[('Burger', 'Burger'), ('Tacos', 'Tacos'), ('Pizza', 'Pizza'), ('Salade', 'Salade'), ('Pâtes', 'Pâtes'), ('Kebab', 'Kebab'), ('Risotto', 'Risotto'), ('Indien', 'Indien'), ('Sushis', 'Sushis'), ('Chinois', 'Chinois'), ('Tex Mex', 'Tex Mex')], max_length=20, null=True),
        ),
    ]
