# Generated by Django 2.0.3 on 2019-08-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0114_auto_20190822_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sharable_user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
