# Generated by Django 2.0.3 on 2019-01-03 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_content_a', models.TextField(blank=True, max_length=200, null=True)),
                ('notification_content_b', models.TextField(blank=True, max_length=200, null=True)),
                ('neighborhood', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(55, 'LE PERREUX-SUR-MARNE'), (255, 'SAUMUR'), (305, 'PAU'), (206, 'LEHAVRE'), (205, 'HOUILLES'), (355, 'EPINAL'), (105, 'PLEASE'), (155, 'VERNON'), (2, 'MANTES-LA-JOLIE'), (5, 'EVREUX')], default=105), size=None)),
                ('test', models.BooleanField(default=True)),
                ('campaign_send_date_time', models.DateTimeField(blank=True, null=True)),
                ('campaign_sent', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
