# Generated by Django 2.0.3 on 2019-01-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0088_citymanager_customer'),
        ('please_marketing_campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcampaign',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='neighborhood',
            field=models.ManyToManyField(to='please_marketing_app.Neighborhood'),
        ),
    ]
