# Generated by Django 2.0.3 on 2019-01-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_campaign', '0002_auto_20190103_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationcampaign',
            old_name='neighborhood',
            new_name='neighborhoods',
        ),
    ]
