# Generated by Django 2.0.3 on 2019-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_campaign', '0003_auto_20190103_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcampaign',
            name='campaign_is_sending',
            field=models.BooleanField(default=False),
        ),
    ]
