# Generated by Django 2.0.3 on 2019-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_campaign', '0005_auto_20190104_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcampaign',
            name='max_order_number',
            field=models.IntegerField(default=0, help_text='Nombre de commandes maximum effectuées par les users ciblés'),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='min_order_number',
            field=models.IntegerField(default=0, help_text='Nombre de commandes minimum effectuées par les users ciblés'),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='campaign_name',
            field=models.CharField(default='Test', help_text='Nommer la campagne', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='notification_content_a',
            field=models.TextField(default='Test', help_text='A REMPLIR OBLIGATOIREMENT - Liste des tags : [first_name], [last_name], [emoji.short_code.emoji] Exemple => [emoji.heart_eyes.emoji]', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='notification_content_b',
            field=models.TextField(default='Test', help_text='A REMPLIR OBLIGATOIREMENT - Liste des tags : [first_name], [last_name], [emoji.short_code.emoji] Exemple => [emoji.heart_eyes.emoji]', max_length=200),
            preserve_default=False,
        ),
    ]
