# Generated by Django 2.0.3 on 2019-01-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0088_citymanager_customer'),
        ('please_marketing_campaign', '0006_auto_20190129_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantLaunchCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BooleanField(default=True)),
                ('campaign_send_date_time', models.DateTimeField(blank=True, null=True)),
                ('campaign_is_sending', models.BooleanField(default=False, help_text='NE PAS TOUCHER')),
                ('campaign_sent', models.BooleanField(default=False, help_text='NE PAS TOUCHER')),
                ('email_image', models.ImageField(upload_to='merchant_launch_campaign/email_image/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='please_marketing_app.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Nommer la campagne', max_length=50)),
                ('sms_content_a', models.TextField(help_text='A REMPLIR OBLIGATOIREMENT - Liste des tags : [first_name], [last_name], [emoji.short_code.emoji] Exemple => [emoji.heart_eyes.emoji]', max_length=200)),
                ('sms_content_b', models.TextField(help_text='A REMPLIR OBLIGATOIREMENT - Liste des tags : [first_name], [last_name], [emoji.short_code.emoji] Exemple => [emoji.heart_eyes.emoji]', max_length=200)),
                ('test', models.BooleanField(default=True)),
                ('campaign_send_date_time', models.DateTimeField(blank=True, null=True)),
                ('campaign_is_sending', models.BooleanField(default=False, help_text='NE PAS TOUCHER')),
                ('campaign_sent', models.BooleanField(default=False, help_text='NE PAS TOUCHER')),
                ('max_order_number', models.IntegerField(default=0, help_text='Nombre de commandes maximum effectuées par les users ciblés')),
                ('min_order_number', models.IntegerField(default=0, help_text='Nombre de commandes minimum effectuées par les users ciblés')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('neighborhoods', models.ManyToManyField(to='please_marketing_app.Neighborhood')),
            ],
        ),
    ]
