# Generated by Django 2.0.3 on 2019-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_app', '0098_ltv'),
        ('please_marketing_campaign', '0007_merchantlaunchcampaign_smscampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(help_text='Nommer la campagne', max_length=50)),
                ('script_target', models.CharField(choices=[('RPR', 'Referral Program Remember'), ('NPS', 'Net Promoter Score'), ('FCR', 'Fan Comment Request')], default='RPR', max_length=3)),
                ('test', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign_send_time', models.TimeField(blank=True, null=True)),
                ('campaign_is_sending', models.BooleanField(default=False, help_text='NE PAS TOUCHER')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('neighborhoods', models.ManyToManyField(to='please_marketing_app.Neighborhood')),
            ],
        ),
    ]
