# Generated by Django 2.0.3 on 2019-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_campaign', '0008_croncampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croncampaign',
            name='test',
        ),
    ]
