# Generated by Django 2.0.3 on 2019-06-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('please_marketing_campaign', '0010_auto_20190617_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croncampaign',
            name='script_target',
            field=models.CharField(choices=[('RPR', 'Referral Program Remember'), ('NPS', 'Net Promoter Score'), ('FCR', 'Fan Comment Request'), ('LNA', 'Launch Non Activated Users 15 Days')], default='RPR', max_length=3),
        ),
    ]
